基于python的数据分析

In [2]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: pandas in c:\program files\python312\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in c:\program files\python312\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\program files\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\program files\python312\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\program files\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [5]:
pip install numpy

Requirement already satisfied: numpy in c:\users\lvp\anaconda3\lib\site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import numpy as np

In [4]:
#录入数据框：
#使用字典格式
d = {"姓名": ["刘文涛","王宇翔","田思雨","徐丽娜","丁文彬"],  # 创建学生姓名列
"统计学": [68, 85, 74, 88, 63],              # 写入统计学分数列
"数学": [85, 91, 74, 100, 82],               # 写入数学分数列
"经济学": [84, 63, 61, 49, 89]}              # 写入经济学分数列
df= pd.DataFrame(d)                   # 创建数据框并命名为df 
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [13]:
# 2）使用read_csv读入外部数据
#import pandas as pd
df = pd.read_csv("shu1.csv")  # 加载数据框shu1并命名为df
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [15]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [17]:
df.columns      # 查看所有列名（列索引）

Index(['姓名', '统计学', '数学', '经济学'], dtype='object')

In [19]:
df.dtypes       # 查看所有元素的类型

姓名     object
统计学     int64
数学      int64
经济学     int64
dtype: object

In [21]:
df.head(3)      # 查看前n行数据（默认前5行）

    姓名  统计学  数学  经济学
0  刘文涛   68  85   84
1  王宇翔   85  91   63
2  田思雨   74  74   61

In [23]:
df.info()         # 查看数据结构（索引、数据类型等）

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      5 non-null      object
 1   统计学     5 non-null      int64
 2   数学      5 non-null      int64
 3   经济学     5 non-null      int64
dtypes: int64(3), object(1)
memory usage: 292.0+ bytes

In [25]:
df.shape       # 查看行数和列数（行，列）

(5, 4)

In [27]:
df.T           # 数据框的行列转置

       0    1    2    3    4
姓名   刘文涛  王宇翔  田思雨  徐丽娜  丁文彬
统计学   68   85   74   88   63
数学    85   91   74  100   82
经济学   84   63   61   49   89

In [29]:
df.tail(3)       # 查看后n行数据（默认后5行）

    姓名  统计学   数学  经济学
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [31]:
df.describe()

             统计学          数学        经济学
count   5.000000    5.000000   5.000000
mean   75.600000   86.400000  69.200000
std    10.737784    9.762172  16.769019
min    63.000000   74.000000  49.000000
25%    68.000000   82.000000  61.000000
50%    74.000000   85.000000  63.000000
75%    85.000000   91.000000  84.000000
max    88.000000  100.000000  89.000000

In [33]:
# 选择指定的列
df[['数学']]

    数学
0   85
1   91
2   74
3  100
4   82

In [35]:
df['数学']

0     85
1     91
2     74
3    100
4     82
Name: 数学, dtype: int64

In [37]:
df.values       # 查看所有元素的值

array([['刘文涛', 68, 85, 84],
       ['王宇翔', 85, 91, 63],
       ['田思雨', 74, 74, 61],
       ['徐丽娜', 88, 100, 49],
       ['丁文彬', 63, 82, 89]], dtype=object)

In [39]:
df[['数学','统计学']]    # 选择数学和统计学两列

    数学  统计学
0   85   68
1   91   85
2   74   74
3  100   88
4   82   63

In [41]:
# 选择指定的行
df.loc[2]                # 选择第3行数据,行索引，或写成df.iloc[2]

姓名     田思雨
统计学     74
数学      74
经济学     61
Name: 2, dtype: object

In [45]:
df.loc[[2,4]]            # 选择第3~5行数据，或写成df.iloc[[2,4]]

    姓名  统计学  数学  经济学
2  田思雨   74  74   61
4  丁文彬   63  82   89

In [47]:
df.loc[2:4]            # 连续选择第3行到第5行数据，或写成df[2:]

    姓名  统计学   数学  经济学
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [49]:
# 同时选择多行和多列
dd=df.iloc[[1,3],[0,2,3]]  # 选择第2、4行和第1、3、4列
dd

    姓名   数学  经济学
1  王宇翔   91   63
3  徐丽娜  100   49

In [51]:
dd=df.loc[[1,3],['姓名','数学','经济学']]     # 获取第2、4行和第1、3、4列 # 不能使用：连选 
dd

    姓名   数学  经济学
1  王宇翔   91   63
3  徐丽娜  100   49

In [53]:
df[2:]        # 选择第2行（不含第2行）后的所有行

    姓名  统计学   数学  经济学
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [55]:
df[:2]            # 选择第2行（含第2行）前的所有行

    姓名  统计学  数学  经济学
0  刘文涛   68  85   84
1  王宇翔   85  91   63

In [59]:
df[::2]   # 每隔1行取1行

    姓名  统计学  数学  经济学
0  刘文涛   68  85   84
2  田思雨   74  74   61
4  丁文彬   63  82   89

In [63]:
# 增加列
df1=df['会计学']=[88,75,92,67,78]     # 在数据框的最后插入1列会计学分数，或写成
df1

[88, 75, 92, 67, 78]

In [65]:
df['会计学']=[88,75,92,67,78]
df

    姓名  统计学   数学  经济学  会计学
0  刘文涛   68   85   84   88
1  王宇翔   85   91   63   75
2  田思雨   74   74   61   92
3  徐丽娜   88  100   49   67
4  丁文彬   63   82   89   78

In [67]:
df.loc[:,'会计学']=[88,75,92,67,78]
df

    姓名  统计学   数学  经济学  会计学
0  刘文涛   68   85   84   88
1  王宇翔   85   91   63   75
2  田思雨   74   74   61   92
3  徐丽娜   88  100   49   67
4  丁文彬   63   82   89   78

In [69]:
df = pd.read_csv("shu1.csv") 
df.insert(2,'会计学',[88,75,92,67,78]) 
df

    姓名  统计学  会计学   数学  经济学
0  刘文涛   68   88   85   84
1  王宇翔   85   75   91   63
2  田思雨   74   92   74   61
3  徐丽娜   88   67  100   49
4  丁文彬   63   78   82   89

In [71]:
# 删除数据
df = pd.read_csv("shu1.csv") 
df.drop(['数学'],axis=1,inplace=True)  # 删除指定的列，或写成
df

    姓名  统计学  经济学
0  刘文涛   68   84
1  王宇翔   85   63
2  田思雨   74   61
3  徐丽娜   88   49
4  丁文彬   63   89

In [73]:
df = pd.read_csv("shu1.csv") 
df.drop(labels='数学',axis=1,inplace=True)
df1=df
df1

    姓名  统计学  经济学
0  刘文涛   68   84
1  王宇翔   85   63
2  田思雨   74   61
3  徐丽娜   88   49
4  丁文彬   63   89

In [75]:
df = pd.read_csv("shu1.csv") 
df.drop(labels='数学',axis=1,inplace=True)
df

    姓名  统计学  经济学
0  刘文涛   68   84
1  王宇翔   85   63
2  田思雨   74   61
3  徐丽娜   88   49
4  丁文彬   63   89

In [67]:
df = pd.read_csv("shu1.csv") 
df.drop(index=2,inplace=True)   # 删除第3行数据
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [77]:
# 修改列名称
df = pd.read_csv("shu1.csv") 
df.rename(columns={'数学':'计算机','经济学':'管理学'})  # 将“数学”修改为“计算机”，将“经济学”修改为“管理学”

    姓名  统计学  计算机  管理学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [79]:
# 修改数据
df.iloc[2,1]=85   # 修改第3行（索引2）田思雨的统计学成绩为85
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   85   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [81]:
df.loc[:,'统计学']=[73,90,79,88,68]   # 修改所有学生的统计学成绩为[73,90,79,88,68]
df

    姓名  统计学   数学  经济学
0  刘文涛   73   85   84
1  王宇翔   90   91   63
2  田思雨   79   74   61
3  徐丽娜   88  100   49
4  丁文彬   68   82   89

In [83]:
#转换数据类型，将数值型转换为字符型
df['统计学']=df['统计学'].astype(str)
df

    姓名 统计学   数学  经济学
0  刘文涛  73   85   84
1  王宇翔  90   91   63
2  田思雨  79   74   61
3  徐丽娜  88  100   49
4  丁文彬  68   82   89

In [85]:
df['统计学']=df['统计学'].astype(float)
df

    姓名   统计学   数学  经济学
0  刘文涛  73.0   85   84
1  王宇翔  90.0   91   63
2  田思雨  79.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  68.0   82   89

In [87]:
# 按姓名拼音升序排序数据框
df.sort_values(by='姓名', ascending=True)

    姓名   统计学   数学  经济学
4  丁文彬  68.0   82   89
0  刘文涛  73.0   85   84
3  徐丽娜  88.0  100   49
1  王宇翔  90.0   91   63
2  田思雨  79.0   74   61

In [93]:
my_type=pd.CategoricalDtype(categories=['丁文彬','王宇翔','田思雨','刘文涛','徐丽娜'],
                            ordered=True)          # 设置类别顺序
df['姓名']=df['姓名'].astype(my_type)  # 转换数据框的姓名为有序类
df.sort_values(by='姓名', ascending=True)    # 按姓名笔画升序排序数据框
df

    姓名   统计学   数学  经济学
0  刘文涛  73.0   85   84
1  王宇翔  90.0   91   63
2  田思雨  79.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  68.0   82   89

In [85]:
df.sort_index()

    姓名   统计学   数学  经济学
0  刘文涛  73.0   85   84
1  王宇翔  90.0   91   63
2  田思雨  79.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  68.0   82   89

In [95]:
df.sort_values(by='统计学',ascending=False)   # 按统计学分数降序对整个数据框排序

    姓名   统计学   数学  经济学
1  王宇翔  90.0   91   63
3  徐丽娜  88.0  100   49
2  田思雨  79.0   74   61
0  刘文涛  73.0   85   84
4  丁文彬  68.0   82   89

In [101]:
# 按行合并数据框
import pandas as pd
df1 = pd.read_csv("shu1.csv")                  
df2 = pd.read_csv("shu2.csv")

df = pd.concat([df1, df2]).reset_index(drop=True)
df = pd.concat([df1, df2])
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89
0  李志国   78   84   51
1  王智强   90   78   59
2  宋丽媛   80  100   53
3  袁芳芳   58   51   79
4  张建国   63   70   91

In [103]:
# 按行合并数据框
import pandas as pd
df1 = pd.read_csv("shu1.csv")                  
df2 = pd.read_csv("shu2.csv")

df = pd.concat([df1, df2])
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89
0  李志国   78   84   51
1  王智强   90   78   59
2  宋丽媛   80  100   53
3  袁芳芳   58   51   79
4  张建国   63   70   91

In [105]:
df11=df1.rename(columns={'数学':'计算机','经济学':'管理学'}) 
df11

    姓名  统计学  计算机  管理学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [107]:
df = pd.concat([df11, df2],keys=["df11","df2"])
df

         姓名  统计学    计算机   管理学     数学   经济学
df11 0  刘文涛   68   85.0  84.0    NaN   NaN
     1  王宇翔   85   91.0  63.0    NaN   NaN
     2  田思雨   74   74.0  61.0    NaN   NaN
     3  徐丽娜   88  100.0  49.0    NaN   NaN
     4  丁文彬   63   82.0  89.0    NaN   NaN
df2  0  李志国   78    NaN   NaN   84.0  51.0
     1  王智强   90    NaN   NaN   78.0  59.0
     2  宋丽媛   80    NaN   NaN  100.0  53.0
     3  袁芳芳   58    NaN   NaN   51.0  79.0
     4  张建国   63    NaN   NaN   70.0  91.0

In [109]:
df = pd.concat([df11, df2]).reset_index(drop=True)
df

    姓名  统计学    计算机   管理学     数学   经济学
0  刘文涛   68   85.0  84.0    NaN   NaN
1  王宇翔   85   91.0  63.0    NaN   NaN
2  田思雨   74   74.0  61.0    NaN   NaN
3  徐丽娜   88  100.0  49.0    NaN   NaN
4  丁文彬   63   82.0  89.0    NaN   NaN
5  李志国   78    NaN   NaN   84.0  51.0
6  王智强   90    NaN   NaN   78.0  59.0
7  宋丽媛   80    NaN   NaN  100.0  53.0
8  袁芳芳   58    NaN   NaN   51.0  79.0
9  张建国   63    NaN   NaN   70.0  91.0

In [89]:
df = pd.concat([df11, df2],join="outer")
df

    姓名  统计学    计算机   管理学     数学   经济学
0  刘文涛   68   85.0  84.0    NaN   NaN
1  王宇翔   85   91.0  63.0    NaN   NaN
2  田思雨   74   74.0  61.0    NaN   NaN
3  徐丽娜   88  100.0  49.0    NaN   NaN
4  丁文彬   63   82.0  89.0    NaN   NaN
0  李志国   78    NaN   NaN   84.0  51.0
1  王智强   90    NaN   NaN   78.0  59.0
2  宋丽媛   80    NaN   NaN  100.0  53.0
3  袁芳芳   58    NaN   NaN   51.0  79.0
4  张建国   63    NaN   NaN   70.0  91.0

In [97]:
df = pd.concat([df11, df2],join="inner")
df

    姓名  统计学
0  刘文涛   68
1  王宇翔   85
2  田思雨   74
3  徐丽娜   88
4  丁文彬   63
0  李志国   78
1  王智强   90
2  宋丽媛   80
3  袁芳芳   58
4  张建国   63

In [111]:
# 按列合并数据框
import pandas as pd
df1 = pd.read_csv("shu1.csv")                  
df2 = pd.read_csv("shu2.csv")

df = pd.concat([df1, df2],axis=1).reset_index(drop=True)
df

    姓名  统计学   数学  经济学   姓名  统计学   数学  经济学
0  刘文涛   68   85   84  李志国   78   84   51
1  王宇翔   85   91   63  王智强   90   78   59
2  田思雨   74   74   61  宋丽媛   80  100   53
3  徐丽娜   88  100   49  袁芳芳   58   51   79
4  丁文彬   63   82   89  张建国   63   70   91

In [115]:

df1.iloc[1,0]="王智强"   # 修改第3行（索引2）田思雨的统计学成绩为85
df = pd.concat([df1, df2],axis=1,join="inner" )
df

    姓名  统计学   数学  经济学   姓名  统计学   数学  经济学
0  刘文涛   68   85   84  李志国   78   84   51
1  王智强   85   91   63  王智强   90   78   59
2  田思雨   74   74   61  宋丽媛   80  100   53
3  徐丽娜   88  100   49  袁芳芳   58   51   79
4  丁文彬   63   82   89  张建国   63   70   91

In [117]:
df11=df1.rename(columns={'数学':'计算机','经济学':'管理学','统计学':'统计'}) 
df11

    姓名  统计  计算机  管理学
0  刘文涛  68   85   84
1  王智强  85   91   63
2  田思雨  74   74   61
3  徐丽娜  88  100   49
4  丁文彬  63   82   89

In [119]:
df = pd.merge(df11, df2)#默认以共同的变量合并，如果有多个或没有则返回空值
df

    姓名  统计  计算机  管理学  统计学  数学  经济学
0  王智强  85   91   63   90  78   59

In [121]:
df = pd.merge(df11, df2,how="inner")
df

    姓名  统计  计算机  管理学  统计学  数学  经济学
0  王智强  85   91   63   90  78   59

In [123]:
df = pd.merge(df11, df2,how="outer")#默认以共同的变量合并，如果有多个或没有则返回空值
df

    姓名    统计    计算机   管理学   统计学     数学   经济学
0  丁文彬  63.0   82.0  89.0   NaN    NaN   NaN
1  刘文涛  68.0   85.0  84.0   NaN    NaN   NaN
2  宋丽媛   NaN    NaN   NaN  80.0  100.0  53.0
3  张建国   NaN    NaN   NaN  63.0   70.0  91.0
4  徐丽娜  88.0  100.0  49.0   NaN    NaN   NaN
5  李志国   NaN    NaN   NaN  78.0   84.0  51.0
6  王智强  85.0   91.0  63.0  90.0   78.0  59.0
7  田思雨  74.0   74.0  61.0   NaN    NaN   NaN
8  袁芳芳   NaN    NaN   NaN  58.0   51.0  79.0

In [125]:
df = pd.merge(df11, df2,how="left")#默认以共同的变量合并，如果有多个或没有则返回空值
df

    姓名  统计  计算机  管理学   统计学    数学   经济学
0  刘文涛  68   85   84   NaN   NaN   NaN
1  王智强  85   91   63  90.0  78.0  59.0
2  田思雨  74   74   61   NaN   NaN   NaN
3  徐丽娜  88  100   49   NaN   NaN   NaN
4  丁文彬  63   82   89   NaN   NaN   NaN

In [127]:
df = pd.merge(df11, df2,how="right")#默认以共同的变量合并，如果有多个或没有则返回空值
df

    姓名    统计   计算机   管理学  统计学   数学  经济学
0  李志国   NaN   NaN   NaN   78   84   51
1  王智强  85.0  91.0  63.0   90   78   59
2  宋丽媛   NaN   NaN   NaN   80  100   53
3  袁芳芳   NaN   NaN   NaN   58   51   79
4  张建国   NaN   NaN   NaN   63   70   91

In [129]:
df12=df1.rename(columns={'统计':'统计学'}) 
df12

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王智强   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [131]:
df = pd.merge(df12, df2,how="right",on="姓名")
df

    姓名  统计学_x  数学_x  经济学_x  统计学_y  数学_y  经济学_y
0  李志国    NaN   NaN    NaN     78    84     51
1  王智强   85.0  91.0   63.0     90    78     59
2  宋丽媛    NaN   NaN    NaN     80   100     53
3  袁芳芳    NaN   NaN    NaN     58    51     79
4  张建国    NaN   NaN    NaN     63    70     91

In [133]:
df = pd.merge(df12, df2,how="right",on="统计学")#默认以共同的变量合并，如果有多个或没有则返回空值
df

  姓名_x  统计学  数学_x  经济学_x 姓名_y  数学_y  经济学_y
0  NaN   78   NaN    NaN  李志国    84     51
1  NaN   90   NaN    NaN  王智强    78     59
2  NaN   80   NaN    NaN  宋丽媛   100     53
3  NaN   58   NaN    NaN  袁芳芳    51     79
4  丁文彬   63  82.0   89.0  张建国    70     91

数据的筛选

In [135]:
#########数据的筛选
import pandas as pd
df = pd.read_csv("shu1.csv")   
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [137]:
df[df['统计学']>80]

    姓名  统计学   数学  经济学
1  王宇翔   85   91   63
3  徐丽娜   88  100   49

In [139]:
df.loc[df['统计学'].isin([85,88,90]),:]

    姓名  统计学   数学  经济学
1  王宇翔   85   91   63
3  徐丽娜   88  100   49

In [141]:
df[df['姓名']=='田思雨']

    姓名  统计学  数学  经济学
2  田思雨   74  74   61

In [130]:
df[(df['统计学'] ==88) & (df['数学'] ==100)]

    姓名  统计学   数学  经济学
3  徐丽娜   88  100   49

In [132]:
df[(df['统计学'] >80) & (df['数学']>60)].sort_values(by="经济学")

    姓名  统计学   数学  经济学
3  徐丽娜   88  100   49
1  王宇翔   85   91   63

In [143]:
df[df['统计学'].between(85,100)][['统计学','数学']]

   统计学   数学
1   85   91
3   88  100

随机抽样和数据的随机筛选

In [145]:
import random
d1=df['姓名']
n1 = random.sample(population=list(d1), k=3)   # 无放回抽取10个数据,k为抽样次数
n2 = random.choices(population=d1, k=10)        # 有放回抽取10个数据

print(' 无放回：', n1,'\n','有放回：', n2)

 无放回： ['徐丽娜', '刘文涛', '田思雨']
 有放回： ['王宇翔', '丁文彬', '刘文涛', '丁文彬', '田思雨', '徐丽娜', '王宇翔', '刘文涛', '丁文彬', '田思雨']

In [147]:
df.loc[df['姓名'].isin(n1),:]

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
2  田思雨   74   74   61
3  徐丽娜   88  100   49

生成随机数

In [149]:
# 生成不同分布的随机数
import numpy.random as np

np.seed(15)                              # 设定随机数种子
r1=np.standard_normal(size=5)            # 标准正态分布
r2=np.normal(loc=50,scale=5,size=5)      # 均值(loc)为50、标准差(scale)为5的正态分布
r3=np.uniform(low=0, high=10, size=5)    # 0~10之间的均匀分布

print('# 标准正态分布:','\n',r1,'\n''# 值为50、标准差为5的正态分布:','\n',r2,
      '\n''# 0~10之间的均匀分布:','\n',r3)  # 打印结果

# 标准正态分布:
 [-0.31232848  0.33928471 -0.15590853 -0.50178967  0.23556889]
# 值为50、标准差为5的正态分布:
 [41.18197372 44.52068978 44.56117129 48.47414974 47.63125814]
# 0~10之间的均匀分布:
 [9.17629898 2.64146853 7.17773687 8.65715034 8.07079482]

In [151]:
df['统计学']=df['统计学']+r1
df

    姓名        统计学   数学  经济学
0  刘文涛  67.687672   85   84
1  王宇翔  85.339285   91   63
2  田思雨  73.844091   74   61
3  徐丽娜  87.498210  100   49
4  丁文彬  63.235569   82   89

数据清理：

In [ ]:
#数据去重：

In [155]:
import pandas as pd
df1 = pd.read_csv("shu1.csv")                  
df = pd.concat([df1, df1])
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [167]:
df[df.duplicated(keep=False)]

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [169]:
df_unique = df.drop_duplicates(subset='姓名')
df_unique

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [150]:
df_unique = df.drop_duplicates(keep=False)
df_unique

Empty DataFrame
Columns: [姓名, 统计学, 数学, 经济学]
Index: []

In [173]:
df.iloc[[1],[1]]=78

In [175]:
df_unique = df.drop_duplicates(keep=False)
df_unique

    姓名  统计学  数学  经济学
1  王宇翔   78  91   63
1  王宇翔   85  91   63

In [177]:
df_unique = df.drop_duplicates(keep="first")
df_unique

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   78   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89
1  王宇翔   85   91   63

缺失值的识别和处理

In [179]:
import numpy as np
print(type(np.nan)) # 浮点类型print(type(None))
print(type(None))

<class 'float'>
<class 'NoneType'>

In [181]:
pd.Series([1, np.NAN, 2, None])

0    1.0
1    NaN
2    2.0
3    NaN
dtype: float64

In [185]:
df.iloc[[1],[1]]=np.nan
df

    姓名   统计学   数学  经济学
0  刘文涛  68.0   85   84
1  王宇翔   NaN   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89
0  刘文涛  68.0   85   84
1  王宇翔  85.0   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89

In [187]:
df.isnull()

      姓名    统计学     数学    经济学
0  False  False  False  False
1  False   True  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False
0  False  False  False  False
1  False  False  False  False
2  False  False  False  False
3  False  False  False  False
4  False  False  False  False

In [189]:
df.notnull()

     姓名    统计学    数学   经济学
0  True   True  True  True
1  True  False  True  True
2  True   True  True  True
3  True   True  True  True
4  True   True  True  True
0  True   True  True  True
1  True   True  True  True
2  True   True  True  True
3  True   True  True  True
4  True   True  True  True

In [191]:
df["统计学"].isnull()

0    False
1     True
2    False
3    False
4    False
0    False
1    False
2    False
3    False
4    False
Name: 统计学, dtype: bool

In [193]:
df[df["统计学"].notnull()]

    姓名   统计学   数学  经济学
0  刘文涛  68.0   85   84
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89
0  刘文涛  68.0   85   84
1  王宇翔  85.0   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89

In [195]:
new_df = df.dropna()
new_df

    姓名   统计学   数学  经济学
0  刘文涛  68.0   85   84
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89
0  刘文涛  68.0   85   84
1  王宇翔  85.0   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89

In [197]:
new_df = df.dropna(axis=1)
new_df

    姓名   数学  经济学
0  刘文涛   85   84
1  王宇翔   91   63
2  田思雨   74   61
3  徐丽娜  100   49
4  丁文彬   82   89
0  刘文涛   85   84
1  王宇翔   91   63
2  田思雨   74   61
3  徐丽娜  100   49
4  丁文彬   82   89

In [199]:
df.dropna(subset=["统计学"])

    姓名   统计学   数学  经济学
0  刘文涛  68.0   85   84
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89
0  刘文涛  68.0   85   84
1  王宇翔  85.0   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89

In [201]:
df.dropna(subset=["数学"])

    姓名   统计学   数学  经济学
0  刘文涛  68.0   85   84
1  王宇翔   NaN   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89
0  刘文涛  68.0   85   84
1  王宇翔  85.0   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89

In [203]:
df.fillna(1, inplace = True)
df

    姓名   统计学   数学  经济学
0  刘文涛  68.0   85   84
1  王宇翔   1.0   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89
0  刘文涛  68.0   85   84
1  王宇翔  85.0   91   63
2  田思雨  74.0   74   61
3  徐丽娜  88.0  100   49
4  丁文彬  63.0   82   89

In [205]:
df = pd.read_csv("shu1.csv")
df.iloc[[1],[1]]=np.nan
x = df["统计学"].mean()
df1=df["统计学"].fillna(x)
df1

0    68.00
1    73.25
2    74.00
3    88.00
4    63.00
Name: 统计学, dtype: float64

In [207]:
df = pd.read_csv("shu1.csv")
df.iloc[[1],[1]]=np.nan
x = df["统计学"].median()
df1=df["统计学"].fillna(x)
df1

0    68.0
1    71.0
2    74.0
3    88.0
4    63.0
Name: 统计学, dtype: float64

In [211]:
df = pd.read_csv("shu1.csv")
df.iloc[[1],[1]]=-1
df.drop(1)

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

数据的运算：

In [213]:
import pandas as pd
df = pd.read_csv("shu1.csv")   
df

    姓名  统计学   数学  经济学
0  刘文涛   68   85   84
1  王宇翔   85   91   63
2  田思雨   74   74   61
3  徐丽娜   88  100   49
4  丁文彬   63   82   89

In [215]:
df["比值"]=df["统计学"]/df["数学"]
df

    姓名  统计学   数学  经济学        比值
0  刘文涛   68   85   84  0.800000
1  王宇翔   85   91   63  0.934066
2  田思雨   74   74   61  1.000000
3  徐丽娜   88  100   49  0.880000
4  丁文彬   63   82   89  0.768293

In [217]:
df["总分"]=df["统计学"]+df["数学"]+df["经济学"]
df

    姓名  统计学   数学  经济学        比值   总分
0  刘文涛   68   85   84  0.800000  237
1  王宇翔   85   91   63  0.934066  239
2  田思雨   74   74   61  1.000000  209
3  徐丽娜   88  100   49  0.880000  237
4  丁文彬   63   82   89  0.768293  234