# 描述性统计分析

描述集中趋势的量

In [4]:
# 计算平均数
import pandas as pd
import numpy as np

df = pd.read_csv("shu1.csv")  
df["总分"]=(df["统计学"]+df["数学"]+df["经济学"])/3
df

    姓名  统计学   数学  经济学         总分
0  刘文涛   68   85   84  79.000000
1  王宇翔   85   91   63  79.666667
2  田思雨   74   74   61  69.666667
3  徐丽娜   88  100   49  79.000000
4  丁文彬   63   82   89  78.000000

In [5]:
df.iloc[:,1:].mean()       # 返回每一列的和（无法计算时返回空值）

统计学    75.600000
数学     86.400000
经济学    69.200000
总分     77.066667
dtype: float64

In [6]:
df.select_dtypes(include=["int64"]).mean(axis=1)

0    79.000000
1    79.666667
2    69.666667
3    79.000000
4    78.000000
dtype: float64

In [7]:
df.select_dtypes(include=["int64"]).mean()

统计学    75.6
数学     86.4
经济学    69.2
dtype: float64

In [8]:
df[["统计学","数学","经济学"] ] .mean(axis=1)

0    79.000000
1    79.666667
2    69.666667
3    79.000000
4    78.000000
dtype: float64

In [9]:
df[["统计学","数学","经济学"] ] .mean()

统计学    75.6
数学     86.4
经济学    69.2
dtype: float64

In [10]:
df = pd.read_csv("shu1.csv")  
df.iloc[:,1:]

   统计学   数学  经济学
0   68   85   84
1   85   91   63
2   74   74   61
3   88  100   49
4   63   82   89

In [11]:
df["个数"]=[2,3,4,1,2]
df

    姓名  统计学   数学  经济学  个数
0  刘文涛   68   85   84   2
1  王宇翔   85   91   63   3
2  田思雨   74   74   61   4
3  徐丽娜   88  100   49   1
4  丁文彬   63   82   89   2

In [12]:
#加权平均数
# 使用numpy中的average函数计算加权平均数
import pandas as pd
import numpy as np

m=df['统计学']
f=df['个数']
x_bar=np.average(a=m,weights=f) # 使用average函数计算加权平均数
print('加权平均数 =',x_bar)     # 打印结果

加权平均数 = 75.08333333333333

In [13]:
#中位数
df.iloc[:,1:].median()    # 返回每一列的中位数

统计学    74.0
数学     85.0
经济学    63.0
个数      2.0
dtype: float64

In [14]:
df.iloc[:,1:].quantile([0.25,0.5,0.75])    # 返回分位数

       统计学    数学   经济学   个数
0.25  68.0  82.0  61.0  2.0
0.50  74.0  85.0  63.0  2.0
0.75  85.0  91.0  84.0  3.0

In [15]:
df.select_dtypes(include=["int64"])

   统计学   数学  经济学  个数
0   68   85   84   2
1   85   91   63   3
2   74   74   61   4
3   88  100   49   1
4   63   82   89   2

In [16]:
pd.DataFrame.quantile(df.iloc[:,1:],q=[0.25,0.5,0.75],interpolation='linear')

       统计学    数学   经济学   个数
0.25  68.0  82.0  61.0  2.0
0.50  74.0  85.0  63.0  2.0
0.75  85.0  91.0  84.0  3.0

In [17]:
#计算众数
df = pd.read_csv("shu1.csv") 
df.iloc[1,1]=88
df.iloc[2,1]=88
df["统计学"].mode()

0    88
Name: 统计学, dtype: int64

描述离散程度的统计量

In [18]:
######计算极差和四分位差
df = pd.read_csv("shu1.csv") 
R=df['统计学'].max() - df['统计学'].min()  # 计算极差
IQR=np.quantile(df['统计学'], q=0.75) -np.quantile(df['统计学'], q=0.25  )# 计算四分位差                                                     
print('极差 =',R,'\nIQR =',IQR)  # 使用print函数输出结果

极差 = 25
IQR = 17.0

In [19]:
######计算极差和四分位差
IQR=df['统计学'].quantile(0.75)-df['统计学'].quantile(0.25)
print('IQR =',IQR)  # 使用print函数输出结果

IQR = 17.0

In [20]:
####方差和标准差
df = pd.read_csv("shu1.csv") 
var = df['统计学'].var()    # 计算方差
sd=df['统计学'].std()          # 计算标准差
print('方差 =',round(var,4),'\n标准差 =',round(sd,4))

方差 = 115.3
标准差 = 10.7378

In [21]:
####变量间的比较
df = pd.read_csv("shu1.csv") 
df["打分"]=[2,3,4,1,2]
mean =df.iloc[:,1:].mean()    # 计算方差
var =df.iloc[:,1:].var()    # 计算方差
sd=df.iloc[:,1:].std()          # 计算标准差
print('均值 =',round(mean,4),'\n标准差 =',round(sd,4))

均值 = 统计学    75.6
数学     86.4
经济学    69.2
打分      2.4
dtype: float64
标准差 = 统计学    10.7378
数学      9.7622
经济学    16.7690
打分      1.1402
dtype: float64

In [22]:
#数据标准化1：计算标准分数
from scipy import stats         # scipy是基于numpy的科学计算包
df = pd.read_csv("shu1.csv") 
df["打分"]=[1,10,9,5,2]
df["标化统计"] = stats.zscore(df['统计学'])  # ddof是自由度
df["标化打分"] = stats.zscore(df['打分'])  # ddof是自由度
#print('标准分数：','\n',np.round(df, 4))
df

    姓名  统计学   数学  经济学  打分      标化统计      标化打分
0  刘文涛   68   85   84   1 -0.791323 -1.218467
1  王宇翔   85   91   63  10  0.978742  1.273852
2  田思雨   74   74   61   9 -0.166594  0.996928
3  徐丽娜   88  100   49   5  1.291106 -0.110770
4  丁文彬   63   82   89   2 -1.311931 -0.941543

In [23]:
df[["统计学","标化统计","打分","标化打分"]].std()          # 计算标准差

统计学     10.737784
标化统计     1.118034
打分       4.037326
标化打分     1.118034
dtype: float64

In [24]:
#数据标准化2 ：计算极值标准化值:
import numpy as np
df = pd.read_csv("shu1.csv") 
# 计算极值标准化值
x=df['统计学']
T = (x-min(x))/(max(x)-min(x))
#print('极值标准化值：','\n',np.array(round(T, 4)))
T

0    0.20
1    0.88
2    0.44
3    1.00
4    0.00
Name: 统计学, dtype: float64

In [25]:
# 计算变异系数
df = pd.read_csv("shu1.csv") 
mean = df['统计学'].mean()    # 计算平均数
sd = df['统计学'].std()       # 计算标准差
cv = sd /mean               # 计算变异系数
cv
print({"平均数": mean, "标准差": sd, "变异系数": cv})  # 生成结果数据框

{'平均数': np.float64(75.6), '标准差': np.float64(10.737783756436894), '变异系数': np.float64(0.1420341766724457)}

计算分布形状的统计量

In [26]:
########计算偏度系数和峰度系数
df = pd.read_csv("shu1.csv") 
skew = df['统计学'].skew()  # 计算偏度系数
kurt = df['统计学'].kurt()  # 计算峰度系数
print("偏度系数 =", round(skew, 4),'\n'"峰度系数 =", round(kurt, 4))

偏度系数 = 0.0989
峰度系数 = -2.3587

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      5 non-null      str
 1   统计学     5 non-null      int64
 2   数学      5 non-null      int64
 3   经济学     5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes

In [28]:
df.agg({'统计学':'max','数学':'max'})

统计学     88
数学     100
dtype: int64

In [29]:
df.agg({'统计学':['min','mean','max'],'数学':['min','mean','max']})

       统计学     数学
min   63.0   74.0
mean  75.6   86.4
max   88.0  100.0

In [30]:
df.iloc[:,1:].agg(["count",'min','mean','max','skew','kurt'])

             统计学          数学        经济学
count   5.000000    5.000000   5.000000
min    63.000000   74.000000  49.000000
mean   75.600000   86.400000  69.200000
max    88.000000  100.000000  89.000000
skew    0.098864    0.276890   0.174257
kurt   -2.358665    0.076161  -2.085097

数值变量间的相关性

In [31]:
#数值变量的相关性
df = pd.read_csv("shu1.csv") 
df.iloc[:,1:].corr()

          统计学        数学       经济学
统计学  1.000000  0.710237 -0.913018
数学   0.710237  1.000000 -0.472505
经济学 -0.913018 -0.472505  1.000000

二、类别数据的描述性统计

In [32]:
#一维频数表
# 使用value.counts()函数生成专业的简单频数表
import pandas as pd
df = pd.read_csv("shu3.csv") 
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      50 non-null     str
 1   性别      50 non-null     str
 2   专业      50 non-null     str
 3   满意度     50 non-null     str
 4   考试分数    50 non-null     int64
dtypes: int64(1), str(4)
memory usage: 2.1 KB

    姓名 性别   专业  满意度  考试分数
0  张青松  男  会计学  不满意    82
1  王宇翔  男  金融学   一般    81
2  田思雨  女  会计学   满意    75
3  徐丽娜  女  管理学   一般    86
4  张志杰  男  会计学  不满意    77

In [33]:
df.describe()

            考试分数
count  50.000000
mean   78.760000
std     9.503082
min    51.000000
25%    74.250000
50%    79.000000
75%    84.750000
max    98.000000

In [34]:
tab1=df['专业'].value_counts()     # 生成频数表（类型是序列）
pd.DataFrame(tab1)               # 转换成数据框

     count
专业
会计学     19
金融学     16
管理学     15

In [35]:
# 将频数表转化成百分比表
tab2=pd.DataFrame(df['专业'].value_counts(normalize=True)*100)
tab2

     proportion
专业
会计学        38.0
金融学        32.0
管理学        30.0

In [36]:
tab2=pd.DataFrame(df['专业'].value_counts(normalize=True))
tab2

     proportion
专业
会计学        0.38
金融学        0.32
管理学        0.30

In [37]:
df.pivot_table(index='专业',aggfunc='count')

     姓名  性别  满意度  考试分数
专业
会计学  19  19   19    19
管理学  15  15   15    15
金融学  16  16   16    16

In [38]:
# 使用pd中的crosstab函数生成二维表
tab1=pd.crosstab(df.性别,df.满意度)
tab1

满意度  一般  不满意  满意
性别
女     3    6  13
男    12    6  10

In [39]:
# 为二维表添加边际和并修改边际和的名称
tab22=pd.crosstab(df.性别,df.满意度,margins=True,margins_name='合计')
tab22

满意度  一般  不满意  满意  合计
性别
女     3    6  13  22
男    12    6  10  28
合计   15   12  23  50

In [40]:
# 将二维表转换成百分比表
tab23=pd.crosstab(df.性别,df.满意度,margins=True,
                 margins_name='合计',normalize='index')
round(tab23*100,2)     # 转换成百分比表，结果保留2位小数

满意度     一般    不满意     满意
性别
女    13.64  27.27  59.09
男    42.86  21.43  35.71
合计   30.00  24.00  46.00

In [41]:
# 计算各列所占的比例，并转换成百分比表
tab24=pd.crosstab(df.性别,df.满意度,margins=True,margins_name='合计',normalize='columns')
round(tab24*100,2)

满意度    一般   不满意     满意    合计
性别
女    20.0  50.0  56.52  44.0
男    80.0  50.0  43.48  56.0

In [42]:
# 计算各数据占总和的比例，并转换成百分比表
tab25=pd.crosstab(df.性别,df.满意度,margins=True,margins_name='合计',normalize='all')
tab25*100

满意度    一般   不满意    满意     合计
性别
女     6.0  12.0  26.0   44.0
男    24.0  12.0  20.0   56.0
合计   30.0  24.0  46.0  100.0

In [43]:
df.groupby('专业').groups

{'会计学': [0, 2, 4, 7, 9, 13, 14, 16, 27, 29, 30, 32, 33, 34, 35, 39, 47, 48, 49], '管理学': [3, 6, 12, 17, 18, 20, 22, 25, 36, 37, 38, 41, 42, 45, 46], '金融学': [1, 5, 8, 10, 11, 15, 19, 21, 23, 24, 26, 28, 31, 40, 43, 44]}

In [44]:
df.groupby('专业').describe()

     考试分数
    count       mean        std   min   25%   50%    75%   max
专业
会计学  19.0  77.368421  11.456248  51.0  74.0  79.0  83.50  98.0
管理学  15.0  80.333333   6.043493  71.0  76.0  79.0  85.50  91.0
金融学  16.0  78.937500   9.922827  55.0  74.0  80.5  83.25  97.0

In [45]:
df.pivot_table(values="考试分数",
index='专业',columns=
'满意度',aggfunc='count')

满意度  一般  不满意  满意
专业
会计学   5    6   8
管理学   6    4   5
金融学   4    2  10

In [46]:
# 性别和专业为行变量，满意度为列变量（行变量和列变量根据需要确定）
df = pd.read_csv("shu3.csv") 
df.drop(['姓名','考试分数'],axis=1,inplace=True)  # 删除姓名列和考试分数列
tab1 = pd.pivot_table(df,index=['性别','专业'],   # 设置行变量
             columns=['满意度'],                  # 设置列变量
             margins=True, margins_name='合计',   # 添加边际和并重命名为“合计”
             aggfunc=len)                         # 使用长度聚集函数
tab1

满意度     一般  不满意  满意  合计
性别 专业
女  会计学   1    3   5   9
   管理学   1    2   1   4
   金融学   1    1   7   9
男  会计学   4    3   3  10
   管理学   5    2   4  11
   金融学   3    1   3   7
合计      15   12  23  50

In [47]:
df

   性别   专业  满意度
0   男  会计学  不满意
1   男  金融学   一般
2   女  会计学   满意
3   女  管理学   一般
4   男  会计学  不满意
5   女  金融学   满意
6   男  管理学   一般
7   女  会计学   一般
8   女  金融学   满意
9   男  会计学   一般
10  女  金融学  不满意
11  男  金融学   满意
12  男  管理学   一般
13  男  会计学   满意
14  男  会计学  不满意
15  女  金融学   满意
16  男  会计学   满意
17  男  管理学   一般
18  女  管理学   满意
19  男  金融学   满意
20  男  管理学  不满意
21  男  金融学   一般
22  女  管理学  不满意
23  男  金融学   一般
24  男  金融学  不满意
25  男  管理学   一般
26  女  金融学   满意
27  男  会计学   一般
28  女  金融学   满意
29  女  会计学  不满意
30  女  会计学   满意
31  女  金融学   满意
32  男  会计学   满意
33  男  会计学   一般
34  女  会计学   满意
35  女  会计学  不满意
36  男  管理学   满意
37  男  管理学   满意
38  男  管理学   一般
39  女  会计学  不满意
40  男  金融学   满意
41  男  管理学   满意
42  男  管理学  不满意
43  女  金融学   满意
44  女  金融学   一般
45  女  管理学  不满意
46  男  管理学   满意
47  男  会计学   一般
48  女  会计学   满意
49  女  会计学   满意

In [48]:
# 满意度为行变量，性别和专业为列变量
tab2 = pd.pivot_table(df,index=['满意度'],columns=['性别','专业'],
              margins=True, margins_name='合计',aggfunc=len)
tab2

性别    女           男          合计
专业  会计学 管理学 金融学 会计学 管理学 金融学
满意度
一般    1   1   1   4   5   3  15
不满意   3   2   1   3   2   1  12
满意    5   1   7   3   4   3  23
合计    9   4   9  10  11   7  50

In [49]:
#分组的连续变量
df = pd.read_csv("shu3.csv") 
df.groupby('专业').describe()

     考试分数
    count       mean        std   min   25%   50%    75%   max
专业
会计学  19.0  77.368421  11.456248  51.0  74.0  79.0  83.50  98.0
管理学  15.0  80.333333   6.043493  71.0  76.0  79.0  85.50  91.0
金融学  16.0  78.937500   9.922827  55.0  74.0  80.5  83.25  97.0